#配置数据库的连接信息
spring:
  application:
    name: web-management
  datasource:
    url: jdbc:mysql://localhost:3306/dream01
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

#mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
